#ifndef HAM_PARSE_PARSEEXCEPTION_HPP
#define HAM_PARSE_PARSEEXCEPTION_HPP

namespace ham::parse
{
enum ParseException : unsigned char {
	CONJUNCTION_IN_DISJUNCTION,
	DISJUNCTION_IN_CONJUNCTION,
	ELSE_MISSING_BLOCK,
	FOR_MISSING_BLOCK,
	FOR_MISSING_IDENTIFIER,
	FOR_MISSING_IN,
	FOR_MISSING_LEAF,
	IF_MISSING_BLOCK,
	IF_MISSING_CONDITION,
	INVALID_BRACKET_BLOCK,
	INVALID_BRACKET_EXPRESSION,
	INVALID_IDENTIFIER,
	INVALID_REPLACER_ARGUMENT,
	INVALID_SUBSCRIPT,
	MISSING_CLOSING_CURLY_BRACE,
	MISSING_CLOSING_PAREN,
	MISSING_CLOSING_SQUARE_BRACE,
	MISSING_CONDITIONAL_AFTER_CONJUNCTION,
	MISSING_CONDITIONAL_AFTER_DISJUNCTION,
	MISSING_GROUPED_CONDITIONAL,
	MISSING_VARIABLE_EXPRESSION,
	MISSING_VARIABLE_EXPRESSION_OR_ESCAPE,
	MISSING_VARIABLE_MODIFIER,
	TARGET_STATEMENT_MISSING_TARGET,
	WHILE_MISSING_BLOCK,
	WHILE_MISSING_CONDITION,
	RULE_DEF_MISSING_BLOCK
};
} // namespace ham::parse

#endif // HAM_PARSE_PARSEEXCEPTION_HPP
